### ISSUE TITLE
如何在命令行中浏览'wtf_python'?

### ISSUE THREAD

**Issue by jqu224** [leisurelicht/wtfpython-cn#10]
import wtf_python 成功之后怎么查看 module 里面的内容呢？

谢谢。

**Comment by leisurelicht** [comment]
那个并不是作为包导入使用的，而是命令行命令。

**Comment by jqu224** [comment]
不好意思，还是有点不太明白，可否举个例子呢？
```
>>pip install wtfpython -U
 Requirement already up-to-date: wtfpython in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (0.2)

```
接下去怎么操作？


万分感谢。

**Comment by leisurelicht** [comment]
![tty](https://user-images.githubusercontent.com/8042345/50384617-2e528600-0702-11e9-9c50-c60c4458961d.gif)

像这样，直接在命令行里输命令wtfpython就行了。

我不是很推荐这种阅读途径，因为命令行没法渲染markdown语法，你看到的是markdown原文件，会比较累，所以我也没有将中文版打包。
