### ISSUE TITLE
『Strings can be tricky sometimes/微妙的字符串 *』中 问题

### ISSUE THREAD

**Issue by zhjr2019** [leisurelicht/wtfpython-cn#16]
作者：您好，我发现『Strings can be tricky sometimes/微妙的字符串 *』中
问题1：
```
>>> 'a' * 21 is 'aaaaaaaaaaaaaaaaaaaaa'
False
```
而我运行结果：
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 'a' * 21 is 'aaaaaaaaaaaaaaaaaaaaa'
True
```
与您的结果相反，请问为什么呢？难道是“只有长度小于 20 的字符串才会发生常量折叠”结论不适用了么？
问题2：
[博客](https://www.cnblogs.com/leisurelylicht/p/Python-zhong-shen-mi-de5dao256.html)中最后的代码：
```
>>> a,b = 400,400
>>> id(a) == id(b)
True
```
而我允许结果为：
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a, b = 400, 400
>>> id(a) == id(b)
False
```
结果也是相反的。

**Comment by leisurelicht** [comment]
第一个问题应该是由于 Python 从 3.7 开始不再使用 `peephole optimization`  ， 而是使用新的 [AST Optimizer](https://docs.python.org/3/whatsnew/3.7.html#optimizations) 技术。

博客中的这个问题也是在Python3.6时代提出的，3.7 应该是也修改了实现方式。

**Comment by kangkang59812** [comment]
'wtf'的例子，这不是3个字符吗？为什么解释里说是 0个或1个才字符驻存？

**Comment by leisurelicht** [comment]
> 'wtf'的例子，这不是3个字符吗？为什么解释里说是 0个或1个才字符驻存？

不是长度为0或1的“才”驻留，而是长度为0或1的字符串“都”驻留。比如，如果长度大于1 的的字符串中如果包含`！`就不会被驻留，但是字符串是只有一个`！`的长度为1的字符串，就会被驻留。

**Comment by S-N-O-R-L-A-X** [comment]
` a='wtf!'
    b='wtf!'
    print(a is b)
    c,d='wtf!','wtf!'
    print(c is d)`
我得到的结果均为True（python3.9.6）
