### ISSUE TITLE
 Class attributes and instance attributes/类属性和实例属性

### ISSUE THREAD

**Issue by mj2602594534** [leisurelicht/wtfpython-cn#17]
你好,辛苦你给大家翻译这么棒的Python知识

翻译小改进;
       因此, 修改一个实例的属性会影响其他实例和类属性.
----->因此,在这种情况下, 修改一个实例的属性会影响其他实例和类属性.

**Comment by leisurelicht** [comment]
不好意思，最近沉迷游戏，迟迟没有处理。
感谢你提的修改建议。我觉得确实提高了可读性。
我会进行修改并将你加入贡献者名单中。

**Comment by leisurelicht** [comment]
sorry, 拖了很久才更新。

我已更新翻译内容并将您加入贡献列表中，您可以在[这里](https://github.com/leisurelicht/wtfpython-cn/blob/master/CONTRIBUTORS.md)查看。
