### ISSUE TITLE
Subclass relationships/子类关系 *  的翻译

### ISSUE THREAD

**Issue by mj2602594534** [leisurelicht/wtfpython-cn#19]
原话:
        Python 中的子类关系并不必须是传递的. 任何人都可以在元类中随意定义 __subclasscheck__.
当 issubclass(cls, Hashable) 被调用时, 它只是在 cls 中寻找 "__hash__" 方法或继承自"__hash__"的方法.
修改:
       Python 中的子类关系并不必须是传递的---->Python 中的子类关系不一定是传递的
       它只是在 cls 中寻找 "__hash__" 方法或继承自"__hash__"的方法.  -----> 它只是在 cls 中寻找 "__hash__" 方法或者去继承的父类中寻找"__hash__"的方法.

**Comment by leisurelicht** [comment]
感谢你的贡献，我已更新翻译内容并将您加入贡献列表中，您可以在[这里](https://github.com/leisurelicht/wtfpython-cn/blob/master/CONTRIBUTORS.md)查看。
