### ISSUE TITLE
is is not what it is!/出人意料的is!

### ISSUE THREAD

**Issue by dingqiulin** [leisurelicht/wtfpython-cn#21]
is 运算符检查两个运算对象是否引用自同一对象 (即, 它检查两个预算对象是否相同).
-----------------------------------
"预算"应该改为“运算”

**Comment by leisurelicht** [comment]
感谢你的贡献，我已更新翻译内容并将您加入贡献列表中，您可以在[这里](https://github.com/leisurelicht/wtfpython-cn/blob/master/CONTRIBUTORS.md)查看。
