### ISSUE TITLE
一个未配对的括号

### ISSUE THREAD

**Issue by myfreess** [leisurelicht/wtfpython-cn#23]
字符串在编译时被实现 `('wtf' `将被驻留, 但是 `''.join(['w', 't', 'f'] `将不会被驻留)

**Comment by leisurelicht** [comment]
感谢你的贡献，我已更新翻译内容并将您加入贡献列表中，您可以在[这里](https://github.com/leisurelicht/wtfpython-cn/blob/master/CONTRIBUTORS.md)查看。
