### ISSUE TITLE
>>> 0.4-0.3 结果为啥是 0.10000000000000003

### ISSUE THREAD

**Issue by Cuick** [leisurelicht/wtfpython-cn#30]
![image](https://user-images.githubusercontent.com/6441929/64600704-2f415a00-d3ee-11e9-85ee-805e68216be8.png)

有没有大佬解释一下这是啥原因呢？

**Comment by Cuick** [comment]
知道了

**Comment by AsiaLi** [comment]
二进制表示浮点数会有截断误差 就是精度的问题 是正常的
问题是 如果我们想比较 0.1+0.2 之后的数值是否和0.3相等 
也就是说从程序员的角度看 他们应该是相等的 输出是true
但是如果从计算机的角度看他们可能不等 那怎么解决呢？

**Comment by AsiaLi** [comment]
这个里面有个方法 只能比较很接近的情况下 认为相等https://stackoverflow.com/questions/5595425/what-is-the-best-way-to-compare-floats-for-almost-equality-in-python
