### ISSUE TITLE
字符串缓存中注释存在错误?

### ISSUE THREAD

**Issue by pruidong** [leisurelicht/wtfpython-cn#32]
``` 
>>>a, b = "wtf!", "wtf!"
>>>a is b # 仅适用于3.7版本以下, 3.7以后的返回结果为False.
True
```

上述代码在Python 3.8中运行同样为True.注释存在错误.

运行环境: IDLE / Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32

相关连接地址.

https://github.com/leisurelicht/wtfpython-cn#-strings-can-be-tricky-sometimes%E5%BE%AE%E5%A6%99%E7%9A%84%E5%AD%97%E7%AC%A6%E4%B8%B2-

**Comment by leisurelicht** [comment]
我本地下载个3.8试一下

**Comment by pruidong** [comment]
```
>>> [(yield x) for x in some_iterable]
SyntaxError: 'yield' inside list comprehension
>>> [(yield x) for x in some_iterable]
SyntaxError: 'yield' inside list comprehension
>>> list([(yield x) for x in some_iterable])
SyntaxError: 'yield' inside list comprehension
>>> list((yield x) for x in some_iterable)
SyntaxError: 'yield' inside generator expression
>>> list(some_func((yield x)) for x in some_iterable)
SyntaxError: 'yield' inside generator expression
```
3.8中的idle运行上面的语句报错.

https://github.com/leisurelicht/wtfpython-cn#-yielding-none%E7%94%9F%E6%88%90-none

**Comment by leisurelicht** [comment]
> ```
> >>> [(yield x) for x in some_iterable]
> SyntaxError: 'yield' inside list comprehension
> >>> [(yield x) for x in some_iterable]
> SyntaxError: 'yield' inside list comprehension
> >>> list([(yield x) for x in some_iterable])
> SyntaxError: 'yield' inside list comprehension
> >>> list((yield x) for x in some_iterable)
> SyntaxError: 'yield' inside generator expression
> >>> list(some_func((yield x)) for x in some_iterable)
> SyntaxError: 'yield' inside generator expression
> ```
> 
> 
> 3.8中的idle运行上面的语句报错.
> 
> 
> https://github.com/leisurelicht/wtfpython-cn#-yielding-none%E7%94%9F%E6%88%90-none

3.8中把这个bug修复了，看[这里](https://docs.python.org/dev/whatsnew/3.8.html#changes-in-python-behavior).

**Comment by pruidong** [comment]
好的，谢谢.
