### ISSUE TITLE
Sync with English version

### ISSUE THREAD

**Issue by satwikkansal** [leisurelicht/wtfpython-cn#33]
Pushed some updates to https://github.com/satwikkansal/wtfpython 

Would appreciate if anyone can sync the translation accordingly. Also, it is now possible to automatically generate an interactive Jupyter notebook too (from Chinese translation as well). Check out working example on the English repo.

**Comment by leisurelicht** [comment]
No problem, I was busy last few days and I will update this document recently. Thanks.

about Jupyter notebook, It's cool, I need spend some time learning how to use it.

**Comment by satwikkansal** [comment]
Thanks, you can check [this](https://github.com/satwikkansal/wtfpython/issues/195) on generating the jupyter notebook automatically. As long as you add the example id comments (like [this](https://github.com/satwikkansal/wtfpython/blame/master/README.md#L284), it should work out of the box :)
