### ISSUE TITLE
一个错别字...

### ISSUE THREAD

**Issue by xiaoqiangjun** [leisurelicht/wtfpython-cn#42]
在[来做个巨大的字符串吧](https://github.com/leisurelicht/wtfpython-cn/edit/master/README.md#L2265)的说明中。
> 没有像 `add_bytes_with_plus` 一样出现二次增加是因为解释器会如同上一个~~列子~~(例子)所讨论的一样优化.....

**Comment by imba-tjd** [comment]
> 在 Python 中, `str` 是不可变得

的

**Comment by xiaoqiangjun** [comment]
看了半天才发现原来你也是在找错别字，可以很厉害哈哈

**Comment by leisurelicht** [comment]
@xiaoqiangjun @imba-tjd 错误已经修改了，同时将两位加到贡献列表了，希望你们能继续帮助这项目变得更好

@imba-tjd 标题修改的问题我会同步原文修改后再处理，这里就先不处理了
