### ISSUE TITLE
请问代码的运行环境是?

### ISSUE THREAD

**Issue by WangYueScream** [leisurelicht/wtfpython-cn#9]
请问这些代码的运行环境?比如是在 win 还是 linux 还是 Mac 还是 通用于所有平台和Py解释器

**Comment by leisurelicht** [comment]
不明确说明的运行环境都是Python 3.5.2 版本的交互解释器。
只适用于其他版本的情况会在文内说明，如果你在阅读过程中发现有代码在3.5中无法运行且没有明确说明版本的例子，请提个issue，我会确认后补充说明。
如果你确定某个案例在新的Python版本中已无法运行，也欢迎你告诉我。
系统应该是通用的，Python是跨平台的，文章中没有使用只有某一系统能使用第三方库。
